CREATE TABLE IF NOT EXISTS musicians(id SERIAL PRIMARY KEY NOT NULL, name CHARACTER VARYING(40) NOT NULL);
CREATE TABLE IF NOT EXISTS music_genre(id SERIAL PRIMARY KEY NOT NULL, name CHARACTER VARYING(40) NOT NULL);
CREATE TABLE IF NOT EXISTS albums(id SERIAL PRIMARY KEY NOT NULL, name CHARACTER VARYING(40) NOT NULL, year INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS songs(id SERIAL PRIMARY KEY NOT NULL, name CHARACTER VARYING(80) NOT NULL, album_id INTEGER REFERENCES albums(id) NOT NULL, s_dur NUMERIC NOT NULL);
CREATE TABLE IF NOT EXISTS collection(id SERIAL PRIMARY KEY NOT NULL, name CHARACTER VARYING(40) NOT NULL, year INTEGER NOT NULL);


CREATE TABLE IF NOT EXISTS artist_album(
	id SERIAL PRIMARY KEY,
	artist_id INTEGER NOT NULL REFERENCES musicians(id),
	album_id INTEGER NOT NULL REFERENCES albums(id)
);


CREATE TABLE IF NOT EXISTS genre_artist(
	id SERIAL PRIMARY KEY,
	genre_id INTEGER NOT NULL REFERENCES music_genre(id),
	artist_id INTEGER NOT NULL REFERENCES musicians(id)
);

CREATE TABLE IF NOT EXISTS song_collection(
	id SERIAL PRIMARY KEY,
	song_id INTEGER NOT NULL REFERENCES songs(id),
	collection_id INTEGER NOT NULL REFERENCES collection(id)
);